package ie.cit.cad;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class TimeServlet extends HttpServlet {
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		PrintWriter write = resp.getWriter();
		write.print("helo world!!\n");
		
		
		
		Date currentDate = new Date(0, 0, 0) {
		};
		String msg = String.format("(formatting date)current date is %s",
				currentDate);
		write.println(msg);
		write.close();
		// TODO Auto-generated method stub
		//this is autogenerated with the cltl space 
		//super.doGet(req, resp);
	}
}
